-- Crear mantención de comunas + relación a posts (Supabase / Postgres)
--
-- 1) Tabla de comunas: lista editable desde el admin
create table if not exists public.communes (
  slug text primary key,
  label text not null,
  show_in_menu boolean not null default true,
  menu_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Mantener updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_communes_updated_at on public.communes;
create trigger set_communes_updated_at
before update on public.communes
for each row execute function public.set_updated_at();

-- 2) Relación N:N entre posts y comunas
-- Nota: posts.id es uuid en este proyecto.
create table if not exists public.post_communes (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  commune_slug text not null references public.communes(slug) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, commune_slug)
);

create index if not exists idx_post_communes_commune on public.post_communes(commune_slug);
create index if not exists idx_post_communes_post on public.post_communes(post_id);

-- RLS (recomendación):
-- - Lectura pública (anon) de communes y post_communes si el front debe consumirlo.
-- - Escritura solo con service role (lo que ya usa el admin).
-- Configura políticas según tu setup.
